sudo: required

services:
    - docker

before_install:
    - docker pull stevenjackson/android-ndk
    - docker run stevenjackson/android-ndk /bin/bash

notifications:
    email:
        - sj@oscode.net

script:
    - make autotools \
      && ./configure --prefix $HOME/ltp --with-open-posix-testsuite --with-realtime-testsuite \
      && make ANDROID=1 -j$(getconf _NPROCESSORS_ONLN) \
      && make -j$(getconf _NPROCESSORS_ONLN) install
