language: c

sudo: required

services:
    - docker

before_install:
    - docker pull stevenjackson/android-ndk
    - docker cp .travis-ci.sh /root/build.sh
    - docker run -v ~/ltp:/root/ltp stevenjackson/android-ndk /bin/bash

notifications:
    email:
        - sj@oscode.net

script:
    - .travis-ci.sh
