dist: xenial
sudo: required

services:
    - docker

before_install:
    - docker pull stevenjackson/android-ndk
    - docker run --interactive --tty --volume $PWD:/ltp --detach --name build stevenjackson/android-ndk
notifications:
    email:
        - sj@oscode.net

script:
    - docker exec make autotools
    - docker exec ./configure --prefix $HOME/ltp --with-open-posix-testsuite --with-realtime-testsuite
    - docker exec make ANDROID=1 -j$(getconf _NPROCESSORS_ONLN)
    - docker exec make -j$(getconf _NPROCESSORS_ONLN) install
